# Licensed under the P-EADCA Universal Waiver License (PUWL v2.0draft02)
# See LICENSE.puwl in the project root for details.

# https://github.com/bridgecrewio/checkov#configuration-using-a-config-file
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .cache/checkov/.external_modules
framework:
  - all
skip-path:
  - .cache
skip-check:
  - CKV_GHA_7  # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch inputs MUST be empty.
