# Licensed under the P-EADCA Universal Waiver License (PUWL v2.0draft02)
# See LICENSE.puwl in the project root for details.

---
extends: default

ignore: |
  charts/*/templates/

rules:
  line-length:
    # keep in sync with .editorconfig
    max: 120
    level: warning

  # comments-indentation: disable  # don't bother me with this rule
  truthy:
    level: error
    check-keys: false
  document-start: disable
  brackets: { min-spaces-inside: 0, max-spaces-inside: 1 }
  braces: { min-spaces-inside: 0, max-spaces-inside: 1 }
  comments-indentation: false
